name: Python Flask App CI/CD

on:
  push:
    branches:
      - main  # You can adjust this to your branch (e.g., `master` or `main`)
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make run_pipeline.sh executable
      run: chmod +x run_pipeline.sh

    - name: Run pipeline script
      run: ./run_pipeline.sh


